from . import mixins
from . import product_category
from . import sale_order
from . import product
from . import wak_faq
from . import wak_promo
from . import res_users
from . import res_partner
from . import sale_rank
from . import delivery_carrier
from . import wak_catalog